name: DS Tests

on: [push, pull_request]

jobs:
  init:
    name: Initializing Workflow
    runs-on: ubuntu-latest
    container: fedora:latest
    outputs:
      matrix: ${{ steps.init.outputs.matrix }}
      repo: ${{ steps.init.outputs.repo }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Initialize workflow
        id: init
        env:
          BASE64_MATRIX: ${{ secrets.BASE64_MATRIX }}
          BASE64_REPO: ${{ secrets.BASE64_REPO }}
        run: |
          tests/bin/init-workflow.sh

  build:
    name: Building LDAP SDK
    needs: init
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build runner image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            OS_VERSION=${{ matrix.os }}
            COPR_REPO=${{ needs.init.outputs.repo }}
            BUILD_OPTS=--with-timestamp --with-commit-id
          tags: ldapjdk-runner
          target: ldapjdk-runner
          outputs: type=docker,dest=/tmp/ldapjdk-runner.tar

      - name: Upload runner image
        uses: actions/upload-artifact@v2
        with:
          name: ldapjdk-runner-${{ matrix.os }}
          path: /tmp/ldapjdk-runner.tar

  ds-test:
    name: Testing DS
    needs: [init, build]
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/ldapjdk
    strategy:
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Download runner image
        uses: actions/download-artifact@v2
        with:
          name: ldapjdk-runner-${{ matrix.os }}
          path: /tmp

      - name: Load runner image
        run: docker load --input /tmp/ldapjdk-runner.tar

      - name: Run container
        run: |
          IMAGE=ldapjdk-runner \
          NAME=ds \
          HOSTNAME=ds.example.com \
          tests/bin/runner-init.sh

      - name: Install DS package
        run: docker exec ds dnf install -y 389-ds-base

      - name: Create DS instance
        run: docker exec ds ${SHARED}/tests/bin/ds-create.sh

      - name: Verify LDAP tools
        run: docker exec ds ${SHARED}/tests/bin/tools-test.sh

      - name: Gather artifacts
        if: always()
        run: |
          tests/bin/ds-artifacts-save.sh ds

      - name: Remove DS instance
        run: docker exec ds ${SHARED}/tests/bin/ds-remove.sh

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ds-${{ matrix.os }}
          path: |
            /tmp/artifacts/ds
